version: "3"
volumes:
  pg-data:
services:
  bot:
    build: .
    command: ["python", "run.py"]
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
  db:
    image: "postgres:9.6-alpine"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_USER:-bot}
      - POSTGRES_USER=${POSTGRES_PASSWORD:-bot}
      - POSTGRES_DB=bot