version: "3"

volumes:
  onhockey-pg-data:

services:

  bot:
    build: .
    command: ["python", "run.py"]
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    depends_on:
      - db

  db:
    image: "postgres:13.3-alpine"
    volumes:
      - onhockey-pg-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}